name: Dev-CI

on:
  pull_request:
    branches: ['main']
  push:
    branches-ignore: ['main']
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dev-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      # ───────── Python + pip cache ────────────────────────────────
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # ───────── Poetry + deps ─────────────────────────────────────
      - name: Install Poetry
        run: pip install --upgrade poetry

      - name: Install deps (dev extras)
        run: poetry install --with dev

      # ───────── Quality gates ─────────────────────────────────────
      - name: Formatting
        run: poetry run pre-commit run --all-files --hook-stage manual

      - name: Lint (ruff & mypy)
        run: |
          poetry run ruff check .
          poetry run mypy src

      - name: Unit tests + coverage
        run: poetry run pytest --cov --cov-report xml

      - name: Security scan (bandit + pip‑audit)
        run: |
          poetry run bandit -r src -ll
          poetry run pip-audit

      # ───────── Docker build (cacheable) ──────────────────────────
      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx (container driver)
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container      # enables cache‑export
          buildkitd-flags: --debug
          install: true                 # puts `docker buildx` on PATH

      - name: Build docker image (cacheable)
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}  # use the new builder
          context: .
          push: false
          load: false
          platforms: linux/amd64,linux/arm64
          tags: sample:ci
          cache-from: type=gha
          cache-to:   type=gha,mode=max
